config/routes.rb
Hackerhaus::Application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  

  root :to => 'home#index'
  resources :properties
  resource :search, only: [:show]
  
  resource :users

  get "activate/:code" => "users#activate", :as => "activate"
  resource :session
  resource :office

end

app/models/property.rb
require 'elasticsearch/model'

class Property < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :title, :presence => true
  validates :description, :presence => true
  validates :street, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :price, :presence => true
  geocoded_by :address
  after_validation :geocode, :if => :street_changed? || :city_changed? || :state_changed?
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }


  def address
    [street, city, state].compact.join(', ')
  end

  def as_indexed_json(options = nil) 
    self.as_json( only: [ :title, :description, :street, :city ] ) 
  end


  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'description', 'street', 'city']
          }
        }
      }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english'
      indexes :description, analyzer: 'english'
      indexes :city, analyzer: 'english'
    end
  end

end

# Delete the previous properties index in Elasticsearch
Property.__elasticsearch__.client.indices.delete index: Property.index_name rescue nil

# Create the new index with the new mapping
Property.__elasticsearch__.client.indices.create \
  index: Property.index_name,
  body: { settings: Property.settings.to_hash, mappings: Property.mappings.to_hash }

Property.import

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  attr_accessor :email, :is_admin, :name, :role, :activation_code, :password, :password_confirmation

  validates :name, :presence => true
  validates :email, :presence => true

  before_create :create_activation_code
  after_create :send_confirmation_email

  def send_confirmation_email
    UserMailer.confirmation_email(self).deliver
  end

  def create_activation_code
    self.activation_code = random_string(length=10)
  end

  def random_string(length=10)
    (1..length).collect {alphanumeric_characters.sample}.join
  end

  def alphanumeric_characters
    ('a'..'z').to_a + ('0'..'9').to_a
  end

  def is_active?
    self.activation_code == nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def auth_required
    unless current_user
      session[:target_url] = request.fullpath
      redirect_to new_session_path, flash: { error: 'This site is protected.  Please log in.' }
    end
  end

  def access_only_with_roles(*roles)
    if current_user
      unless roles.include? current_user.role
        session[:target_url] = request.fullpath
        redirect_to new_session_path, flash: { warning: 'Access denied.  Insufficient rights.' }
      end
    end
  end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@properties = Property.order("created_at DESC").limit(5)
		# @properties = Property.order("created_at DESC").limit(5)
		@hoods = [ ['SOMA', 'soma.jpg'], ['Castro', 'castro.jpg'], ['North Beach', 'lowernob.jpg'], ['Richmond', 'richmond.jpg'], ['Mission District', 'mission.jpg'], ['Tenderloin', 'tenderloin.jpg']]
	end

end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def show
    auth_required
    access_only_with_roles('agent')
  end
  
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

	def index
		@properties = Property.order("created_at DESC").limit(5)
	end

	def new
		@property = Property.new
		@states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA','MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI']
	end

	def create
		@property = Property.new(property_params)
		if @property.save
			flash[:notice] = "Congratulations.  Your property has been listed with H@ackerhaus."
			redirect_to root_path
		else
			render :new
		end
	end

	def property_params
		params.require(:property).permit(:title, :description, :street, :city, :state, :zip_code, :price, :image)
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  $last_query = ""

  def show
    if !request.xhr?
      $last_query = params[:query]
    end

    if $last_query == ""
      @properties = Property.all
    else
      @properties = Property.search($last_query).records
    end

    @geojson = Array.new

    @properties.each do |listing|
      @geojson << {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [listing.longitude, listing.latitude]
        },
        properties: {
          name: listing.title,
          address: listing.street,
          :'marker-color' => '#00607d',
          :'marker-symbol' => 'circle',
          :'marker-size' => 'medium'
        }
      }
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => @geojson }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email]).try(:authenticate, params[:session][:password])
    if user
      if user.is_active?
        session[:user_id] = user.id
        redirect_to (session[:arget_url] || root_path), notice: 'Successfully logged in.'
      else
        redirect_to new_session_path, flash: { error: 'Account inactive.  Please activate your account.' }
      end
    else
      redirect_to new_session_path, flash: { error: 'Invalid username or password.' }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Successfully logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(:role => 'agent')
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path, notice: 'Sign up complete. Please check your inbox for activation email.'
    else
      render action: "new"
    end
  end

  def activate 
    @user = User.find_by_activation_code(params[:code])
    @user.activation_code = nil
    if @user.save
      redirect_to root_path, notice: "Activation complete. Welcome #{@user.name}"
    else
      render action: 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/home/index.html.erb
<div id="search-box">

  <div class="content">
    <h1 class="home-tagline">Hack your next stay...</h1>
    <h2 class="home-subheader">Search and book listings in your destination of choice</h2>

    <form class="form-search" action="/search" method="GET">
      <div class="input-group">
        <input type="text" name='query' id="term" class='form-control searchinput input-large search-query' placeholder='Enter a neighborhood in San Francisco...'>
        <span class="input-group-btn">
          <button type="submit" class="btn btn-info">Search</button>
        </span>
      </div>
    </form>

  </div>
</div>
 

<div class="container">
  <div class="neighborhoods">
      <% @hoods.each do |hood, pic| %>
        <div class="col-xs-12 col-md-4">
          <div class="thumbnails">
            <a href="/search?query=<%= hood %>">
              <%= image_tag(pic, size: "328x250", class: "img-responsive") %>
            </a>
            <div class="caption">
              <h3><%= hood %></h3>
              <p><a href="#" class="btn btn-info" role="button">Book Tour</a> <a href="#" class="btn btn-default" role="button">Details</a></p>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

<div id="hacker-friends">
</div>

<div class="community">
  <div class="content">
    <h2 class="title">What's so special about co-living?</h1>
    <div class="content-row">
      <div class="content-text pull-left">
        <h3>SYNERGY</h3>
        <p class="blurb">Whether you're a free spirit looking to connect with other like-minded souls or a tech entrepreneur looking to meet other innovators and disruptors, community living is an excellent way to combine your efforts with others in an incredible way.</p>
      </div>
      <div class="content-icon pull-right">
        <%= image_tag("synergy.png", size: "120x120") %>
      </div>
    </div>
    <div class="content-row">
      <div class="content-icon pull-left">
         <%= image_tag("friend4.png", size: "120x120") %>
      </div>
      <div class="content-text pull-right">
        <h3>FRIENDS</h3>
        <p class="blurb">Living in a big city always has its social challenges.  Imagine having 10-20 instant friends to hang out with and an effortless social life as soon as you move in! Humans are incredibly social creatures built to live in groups.  Explore your social potential in one of our incredible communities.</p>
      </div>
    </div>
    <div class="content-row">
      <div class="content-text pull-left">
        <h3>AFFORDABLE HOUSING</h3>
        <p class="blurb">Stop burning money! We all know how UN-affordable San Francisco can be.  Save your money for awesome experiences and other things you need rather than spending your whole paycheck on housing!  Affordable living in San Francisco has never been this easy...</p>
      </div>
      <div class="content-icon pull-right">
        <%= image_tag("moneyburning.png", size: "120x120") %>
      </div>
    </div>
  </div>
</div>

<div id="house-dinner">
</div>

<div class="quote-section">
  <div class="quote-content">
    <h3 class="quote">“If you want to go quickly, go alone. If you want to go far, go together.”</h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackerhaus</title>

  <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />

  <link href="https://fonts.googleapis.com/css?family=Comfortaa:400,700|Gloria+Hallelujah|Poppins:400,700" rel="stylesheet">
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <%= render 'partials/header' %>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <a class="close" data-dismiss="alert">x</a>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">x</a>
        <%= flash[:error] %>
      </div>
    <% end %>
    <% if flash[:warning] %>
      <div class="alert alert-warning">
        <a class="close" data-dismiss="alert">x</a>
        <%= flash[:warning] %>
      </div>
    <% end %>
    
    <%= yield %>
    
  <%= render 'partials/footer' %>

</body>
</html>

app/views/offices/show.html.erb
<div class="page-header">
  <h1>Welcome to your office, <%= current_user.name %></h1>
</div>

app/views/partials/_footer.html.erb
<footer>
  <div class="links">
    <ul class="socials">
      <li>
        <i class="fa fa-facebook fa-5x icon" aria-hidden="true"></i>
      </li>
      <li>
        <i class="fa fa-twitter fa-5x icon" aria-hidden="true"></i>
      </li>
      <li>
        <i class="fa fa-instagram fa-5x icon" aria-hidden="true"></i>
      </li>
      <li>
        <i class="fa fa-pinterest fa-5x icon" aria-hidden="true"></i>
      </li>
    </ul>
  </div>
  <div class="footer-info">
    <p>Hackerhaus is built by israeliTech in San Francisco, CA<span class="fair-housing">
    <%= image_tag("https://d214hhm15p4t1d.cloudfront.net/7_5_8/z/img/icons/fair-housing.png", size: "16x14") %></span><span class="housing-text">Fair Housing & Equal Opportunity</span> <span class="copywrite">© 2017 Hackerhaus, Inc.</span>
    </p> 
  </div>
</footer>

app/views/partials/_header.html.erb
<nav id="nav" class="navbar-default">
  <div class="nav-content">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header logo">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/">
        <%= image_tag("logo.png", size: "50x50") %>
        <h3 class="dba">H@ckerhaus</h3>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
      <ul id="link-list" class="nav navbar-nav navbar-right site-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Explore <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Chinatown</a></li>
            <li><a href="#">Lower Nob</a></li>
            <li><a href="#">SOMA</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Berkeley</a></li>
            <li><a href="#">Oakland</a></li>
          </ul>
        </li>
        <li>
          <% if current_user %>
            <%= link_to "Log Out", "/session", method: "DELETE" %>
          <% else %>
            <%= link_to "Log In", "#" %>
          <% end %>
        </li>
        <li><span >
          <%= link_to "Post Your Rentals", new_property_path, class: "post-rental-btn btn btn-default" %></span>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/properties/index.html.erb
<h1>Properties</h1>
<%= react_component("Map", prerender: false) %>

app/views/properties/new.html.erb
<div class="container-wrapper">
  <div class="container">

    <div class="row">

      <h1 class="form-title">Post Your Rental</h1>

      <div class="col-md-6 col-md-offset-3" >
        <div class="form-wrapper">
          <%= form_for @property, html: { multipart: true } do |f| %>

            <% if @property.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@property.errors.count, "error") %> prohibited this todo from being saved:</h2>

                <ul>
                <% @property.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.text_field :title, class: "form-control", placeholder: "Title", required: true  %>
            </div>
            <div class="form-group">
              <%= f.text_area :description, class: "form-control", size: "30x12", placeholder: "Write your description here...", required: true %>
            </div>
            <div class="form-group">
              <%= f.text_field :street, class: "form-control", placeholder: "Street address", required: true  %>
            </div>
            <div class="form-group col-xs-12 col-sm-6 col-md-4 inline">
                <%= f.text_field :city, class: "form-control", placeholder: "City", required: true  %>
            </div>
            <div class="form-group col-xs-12 col-sm-6 col-md-2 inline">
              <%= f.select :state, @states, selected: "CA", required: true  %>
            </div>
            <div class="form-group col-xs-12 col-sm-6 col-md-3 inline">
                <%= f.text_field :zip_code, class: "form-control", placeholder: "Zip Code", required: true  %>
            </div>
            <div class="form-group">
              <div class="col-xs-12 col-sm-6 col-md-3 inline last">
                <%= f.text_field :price, class: "form-control", placeholder: "Price", required: true  %>
              </div>
            </div>
            <div class="form-group upload">
              <%= f.label :image, "Upload a picture:" %>
              <%= f.file_field :image, label: "Upload a picture:"%>
            </div>
            <%= f.submit "Submit", class: "btn btn-block btn-lg btn-info pull-right" %>
          <% end %>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/searches/show.html.erb
<div class="container-wrapper">
<div class="container">
  <div class="row">

    <div class="list-main col-md-6">
      <% @properties.each do |p| %>
        <div class="listing">
          <div class="listing-pic">
            <% if p.image.file? %>
              <img src="<%= p.image %>" width="175px" height="125px" alt="neighborhood">
            <% else %>
              <img src="https://placehold.it/175x125" width="175px" height="125px" alt="neighborhood">
            <% end %>
          </div>
          <div class="caption">
            <h2><%= p.title %></h2>
            <p><%= p.city %> | $<%= p.price %><p>
            <p><%= truncate(p.description, length: 140) %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="list-secondary">
      <div sticky class="map-container">
        <div class="map">
          <div id='map-one' class='map'></div>
        </div>
      </div>
    </div>

  </div>
</div>
    
</div>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign Up</h1>
</div>
<%= form_for @user, :html => { class: 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <a href="" class="close" data-dismiss="alert">x</a>
      <% for message in @user.errors.full_messages %>
        <%= message %><br />
      <% end %>
    </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_feld :name, class: 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, class: 'control-label' %>
      <div class="controls">
        <%= f.text_feld :email, class: 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, class: 'control-label' %>
      <div class="controls">
        <%= f.text_feld :password, class: 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, class: 'control-label' %>
      <div class="controls">
        <%= f.text_feld :password_confirmation, class: 'text_field' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.hidden_field :role, :value => 'agent' %>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
<% end %>

  